server:
  port: 8080

spring:
  application:
    name: jdbc

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3309/flow?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true&nullCatalogMeansCurrent=true
    username: root
    password: 123456

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

logging:
  level:
    root: INFO
    org.flowable.engine.impl.persistence.entity.*: debug
    org.flowable.task.service.impl.persistence.entity.*: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] [%highlight(%-5level)] %logger - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %level %logger %msg%n"
  file:
    name: /var/logs/flow/spring-boot-logging.log
    max-size: 500MB
    max-history: 720

flowable:
  database-schema-update: false
  async-executor-activate: false
  process:
    servlet:
      path: /service
  form:
    servlet:
      path: /form-api